/* eslint-disable react/no-unescaped-entities */
import Image from "next/image";

const leadership = [
  ["Political Leadership", "His association with the AIADMK has involved working with party cadres, communities and people across different parts of Tamil Nadu."],
  ["Legislative Experience", "As an elected representative, he has brought constituency-level concerns into the legislative and political process."],
  ["Administrative Experience", "His ministerial responsibilities provided experience in government administration, policy implementation and development programmes."],
  ["Organisational Leadership", "His political role extends beyond electoral representation, with a strong focus on strengthening the party organisation and connecting with its grassroots network."],
  ["Continuing the Journey", "With experience gained through years of public life, S. P. Velumani continues to work towards the larger interests of Tamil Nadu and its people."],
];
const vision = [
  ["Strong Infrastructure", "Modern infrastructure is the foundation of economic growth.", "Our focus should be on better roads, transportation, water infrastructure, urban development and connectivity across Tamil Nadu."],
  ["Opportunities for Youth", "Tamil Nadu's youth are its greatest strength.", "Creating opportunities in education, skills, employment, entrepreneurship, technology and emerging industries is essential for the state's future."],
  ["Education for the Future", "Quality education creates long-term social and economic progress.", "The vision is to strengthen educational opportunities and help students prepare for a rapidly changing world."],
  ["Healthcare for Every Family", "Accessible and quality healthcare should remain a priority for every community.", ""],
  ["Empowering Women", "Women play a central role in the social and economic development of Tamil Nadu.", "Greater opportunities, safety, education, entrepreneurship and economic participation can create stronger families and communities."],
  ["Strong Rural Communities", "Rural development is an essential part of Tamil Nadu's progress.", "Villages need strong infrastructure, employment opportunities, education, healthcare and reliable basic amenities."],
  ["Agriculture & Farmers", "Farmers are central to Tamil Nadu's economy and society.", "Supporting agriculture, improving infrastructure and strengthening opportunities for farming communities remain important priorities."],
  ["Technology & Innovation", "Tamil Nadu can lead India's next generation of innovation.", "Technology, startups, digital infrastructure and new industries can create opportunities for millions of young people."],
];
const people = [["Listen", "Understand the concerns of people and communities."], ["Represent", "Take people's voices to the appropriate platforms."], ["Act", "Work towards practical solutions and meaningful development."], ["Deliver", "Focus on outcomes that improve people's lives."]];
const development = [["Urban Tamil Nadu", "Modern cities require better infrastructure, transportation, housing, water management and employment opportunities."], ["Rural Tamil Nadu", "Rural communities need strong connectivity, agriculture support, education, healthcare and local employment."], ["Industrial Growth", "Tamil Nadu's industrial ecosystem can create new opportunities for businesses, entrepreneurs and workers."], ["Digital Tamil Nadu", "Technology can improve governance, education, healthcare and access to public services."], ["Green & Sustainable Development", "Development must also protect natural resources and create a sustainable future for coming generations."]];
const governance = [["Experience", "Years of political and administrative experience."], ["Accessibility", "Maintaining a connection with people and grassroots communities."], ["Responsibility", "Approaching public office with accountability and commitment."], ["Development", "Focusing on practical improvements that benefit communities."]];
const news = [["Political Updates", "Updates from political programmes and organisational activities."], ["Public Activities", "Community interactions and public engagements."], ["Development", "Updates on development-related initiatives."], ["Speeches & Statements", "Important speeches, views and public statements."], ["Media Coverage", "News and interviews featuring S. P. Velumani."]];

function SectionHead({ label, title }: { label: string; title: string }) { return <div className="section-head"><p className="section-label">{label}</p><h2>{title}</h2></div>; }

export default function Home() {
  return <main>
    <header className="site-header">
      <a className="brand" href="#top" aria-label="S. P. Velumani home"><span className="brand-mark">SPV</span><span className="brand-name">S. P. Velumani</span></a>
      <nav className="nav-links" aria-label="Primary navigation"><a href="#about">About</a><a href="#leadership">Leadership</a><a href="#vision">Vision</a><a href="#people">People First</a><a className="nav-cta" href="#connect">Connect</a></nav>
      <details className="mobile-menu"><summary aria-label="Open navigation"><span /><span /></summary><div><a href="#about">About</a><a href="#leadership">Leadership</a><a href="#vision">Vision</a><a href="#people">People First</a><a href="#connect">Connect</a></div></details>
    </header>

    <section className="hero" id="top"><div className="hero-copy">
      <p className="eyebrow"><span>Leadership</span><span>Experience</span><span>Service</span></p><h1>A Leader Committed to the Progress of <em>Tamil Nadu</em></h1>
      <div className="hero-intro"><div><strong>S. P. Velumani</strong><p>Senior Leader, All India Anna Dravida Munnetra Kazhagam (AIADMK)<br />Member of the Tamil Nadu Legislative Assembly</p></div><p>A leader with extensive political and administrative experience, S. P. Velumani has dedicated his public life to serving the people and contributing to the development of Tamil Nadu.</p></div>
      <p className="hero-summary">His journey reflects a commitment to public service, strong grassroots engagement, organisational leadership and the vision of a stronger Tamil Nadu.</p><div className="hero-actions"><a className="button button-primary" href="#about">Know His Journey <span>↗</span></a><a className="button button-secondary" href="#vision">Explore His Vision <span>→</span></a></div>
    </div><aside className="hero-visual"><span className="hero-word" aria-hidden="true">SPV</span><span className="hero-rail" aria-hidden="true">S. P. VELUMANI · TAMIL NADU</span><Image src="/images/sp-velumani-standing-cutout.png" alt="S. P. Velumani" fill priority sizes="(max-width: 960px) 100vw, 38vw" className="hero-photo" /></aside></section>

    <section className="section about" id="about"><SectionHead label="About S. P. Velumani" title="A Journey in Public Service" /><div className="about-layout"><div className="about-image frame-image"><Image src="/images/sp-velumani-portrait-2.jpg" alt="S. P. Velumani seated" fill sizes="(max-width: 800px) 100vw, 40vw" /></div><div className="prose large-prose"><p>S. P. Velumani is a prominent AIADMK leader with extensive experience in electoral politics, government administration and public service.</p><p>His political journey has been built through years of engagement with people, understanding their aspirations and working on issues connected to development and governance.</p><p>From grassroots politics to significant responsibilities in the Government of Tamil Nadu, his career has brought together political leadership and administrative experience.</p><p>He has represented the people in the Tamil Nadu Legislative Assembly and has served in ministerial responsibilities, including the Rural Development and Panchayat Raj portfolio.</p><p>Today, he continues his public journey with a focus on strengthening the organisation, representing people's concerns and contributing to the future of Tamil Nadu.</p></div></div></section>

    <section className="section leadership-section" id="leadership"><SectionHead label="Leadership Journey" title="From Grassroots to State Leadership" /><p className="lead-statement">Leadership is built through experience, responsibility and people's trust.</p><p className="lead-statement muted">S. P. Velumani's political journey has developed over several years of active public life.</p><div className="timeline">{leadership.map(([title,text],i)=><article key={title}><span>{String(i+1).padStart(2,"0")}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>

    <section className="section vision-section" id="vision"><div className="vision-intro"><SectionHead label="Vision for Tamil Nadu" title="Building a Stronger Tamil Nadu" /><div className="prose"><p>Tamil Nadu has a rich history, a talented population and enormous potential.</p><p>The vision is to build a Tamil Nadu that is economically strong, socially inclusive, technologically progressive and full of opportunities for every generation.</p></div></div><div className="vision-grid" role="region" aria-label="Vision priorities. Scroll horizontally to explore all cards.">{vision.map(([title,text,extra],i)=><article className={i===0||i===7?"featured":""} key={title}><span className="card-no">V / {String(i+1).padStart(2,"0")}</span><h3>{title}</h3><p>{text}</p>{extra&&<p>{extra}</p>}</article>)}</div></section>

    <section className="section people-section" id="people"><div className="people-copy"><SectionHead label="People First" title="Public Service Begins With Listening" /><div className="rhythm-copy"><p>Every community has different needs.</p><p>Every family has different aspirations.</p><p>Every generation has different expectations.</p></div><p>Leadership means listening to these voices and turning genuine concerns into meaningful action.</p><p>S. P. Velumani believes that public representatives must remain connected with people — not only during elections, but throughout their public journey.</p></div><div className="people-steps">{people.map(([title,text],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>

    <section className="section development-section"><SectionHead label="Tamil Nadu Development" title="A Vision Beyond Constituencies" /><div className="development-lead"><p>The progress of Tamil Nadu cannot be limited to individual constituencies.</p><p>Every district, city, town and village has a role in the state's development.</p></div><div className="strip-grid">{development.map(([title,text],i)=><article key={title}><span>{String(i+1).padStart(2,"0")}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>

    <section className="section governance-section"><div className="governance-image frame-image"><Image src="/images/sp-velumani-portrait-1.jpg" alt="S. P. Velumani in a leadership portrait" fill sizes="(max-width: 800px) 100vw, 44vw" /></div><div><SectionHead label="Leadership & Governance" title="Experience That Matters" /><div className="prose"><p>Effective governance requires more than ideas.</p><p>It requires experience, organisation, administration and the ability to understand the realities faced by ordinary people.</p><p>S. P. Velumani's experience in public life and government administration has provided an understanding of the challenges involved in implementing development initiatives at scale.</p></div><div className="governance-list">{governance.map(([title,text])=><article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>

    <section className="section focus-section"><div className="focus-block youth"><p className="section-label">Youth</p><h2>The Future Belongs to the Next Generation</h2><p>Tamil Nadu has one of India's strongest and most ambitious young populations.</p><p>Young people should have the confidence and opportunities to build their future here.</p><h3>Our Focus</h3><ul>{["Education","Skill development","Employment","Entrepreneurship","Technology","Innovation","Sports","Leadership opportunities"].map(x=><li key={x}>{x}</li>)}</ul><h3>Empowering Young Tamil Nadu</h3><p>The goal is not simply to create jobs.</p><p>It is to create an environment where young people can <strong>learn, innovate, build businesses, create employment and lead the future.</strong></p></div><div className="focus-block women"><p className="section-label">Women</p><h2>Empowering Women, Strengthening Families</h2><p>The progress of Tamil Nadu is inseparable from the progress of its women.</p><p>Creating opportunities for women in education, employment, entrepreneurship and leadership can strengthen families and communities.</p><h3>Focus Areas</h3><ul>{["Education","Employment","Entrepreneurship","Financial independence","Safety","Healthcare","Leadership"].map(x=><li key={x}>{x}</li>)}</ul></div></section>

    <section className="section rural-section"><div><SectionHead label="Farmers & Rural Communities" title="Strengthening the Backbone of Tamil Nadu" /><p>Tamil Nadu's villages and agricultural communities are an essential part of the state's identity and economy.</p><p>Development must reach beyond major cities.</p><h3>Priorities</h3><ul className="priority-list">{["Better rural infrastructure","Water management","Agricultural support","Rural roads and connectivity","Education","Healthcare","Employment opportunities","Local economic development"].map((x,i)=><li key={x}><span>{String(i+1).padStart(2,"0")}</span>{x}</li>)}</ul></div><div className="rural-quote"><span>RURAL<br/>TAMIL NADU</span><p>Development must reach beyond major cities.</p></div></section>

    <section className="constituency"><div className="constituency-image"><span aria-hidden="true">THONDAMUTHUR</span><Image src="/images/sp-velumani-greeting-cutout.png" alt="S. P. Velumani greeting the public" fill sizes="(max-width: 800px) 100vw, 50vw" /></div><div className="constituency-copy"><SectionHead label="Thondamuthur" title="A Constituency Close to the Heart" /><p>Thondamuthur remains an important part of S. P. Velumani's political journey and public life.</p><p>His connection with the constituency reflects the importance of grassroots politics and direct engagement with people.</p><p>The constituency section of the website can showcase:</p><ul>{["Development activities","Public interactions","Constituency visits","Local initiatives","Community programmes","Updates and announcements"].map(x=><li key={x}>{x}</li>)}</ul><a className="button button-primary" href="#gallery">Explore Thondamuthur <span>↗</span></a></div></section>

    <section className="section service-section"><SectionHead label="Public Service" title="Service Beyond Politics" /><div className="service-layout"><div className="service-copy"><p>Public service is ultimately about people.</p><p>It means being present when communities need support, listening when people raise concerns and working towards solutions.</p><p>The public-service section can showcase verified activities across areas such as:</p></div><div className="service-topics">{["Education","Healthcare","Infrastructure","Welfare","Youth","Women","Rural Development","Community Development"].map((x,i)=><span key={x}><small>0{i+1}</small>{x}</span>)}</div></div></section>

    <section className="section news-section"><SectionHead label="News & Updates" title="Latest From S. P. Velumani" /><p className="news-lead">Stay connected with the latest activities, political programmes, public meetings, development initiatives and statements.</p><h3 className="sub-label">Categories</h3><div className="news-grid">{news.map(([title,text],i)=><article key={title}><span>{String(i+1).padStart(2,"0")}</span><h3>{title}</h3><p>{text}</p><b>→</b></article>)}</div></section>

    <section className="gallery-section" id="gallery"><div className="gallery-head"><SectionHead label="Media & Gallery" title="Moments of Leadership" /><p>Explore photographs and videos from across his public and political journey.</p></div><div className="gallery-grid"><figure className="gallery-tall gallery-cutout"><span aria-hidden="true">LEADERSHIP</span><Image src="/images/sp-velumani-namaste-cutout.png" alt="S. P. Velumani greeting with folded hands" fill sizes="(max-width: 800px) 100vw, 50vw" /></figure><figure><Image src="/images/sp-velumani-standing.jpg" alt="S. P. Velumani standing" fill sizes="(max-width: 800px) 50vw, 25vw" /></figure><figure><Image src="/images/sp-velumani-portrait-2.jpg" alt="S. P. Velumani portrait" fill sizes="(max-width: 800px) 50vw, 25vw" /></figure></div><div className="gallery-categories"><h3>Gallery Categories</h3>{["Political Events","Public Meetings","People's Interactions","Government Activities","Constituency Visits","Party Programmes","Social & Community Events","Speeches","Media Interviews"].map(x=><span key={x}>{x}</span>)}</div></section>

    <section className="connect-section" id="connect"><div className="connect-intro"><p className="section-label">Connect With the Leader</p><h2>Your Voice Matters</h2><p>Leadership begins with listening.</p><p>Whether you have a suggestion, concern, idea or message, your voice deserves to be heard.</p></div><form className="contact-form"><h3>Share Your Voice</h3><label>Name<input name="name" type="text" /></label><label>Mobile Number<input name="mobile" type="tel" /></label><label>District<input name="district" type="text" /></label><label>Constituency<input name="constituency" type="text" /></label><label className="wide">Message<textarea name="message" rows={4} /></label><button type="submit">Submit Your Message <span>↗</span></button></form></section>

    <footer className="footer"><div className="footer-main"><p className="section-label">Final Home Page Message</p><h2>Together, We Build the Future</h2><div className="footer-copy"><p>Tamil Nadu has always been a land of knowledge, enterprise, culture and opportunity.</p><p>Its greatest strength is its people.</p><p>The future of Tamil Nadu must be built by empowering its people, creating opportunities for the next generation, strengthening communities and ensuring development reaches every part of the state.</p></div><p className="signature">S. P. Velumani</p><div className="closing-lines"><p>Leadership with Experience.</p><p>Service with Commitment.</p><p>A Vision for Tamil Nadu.</p></div><a className="button footer-button" href="#connect">Connect With Us <span>↗</span></a></div><div className="footer-bottom"><span>SPV</span><a href="#top">Back to top ↑</a></div></footer>
  </main>;
}
